// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCZP2tdOYiKr8Z6a90O2Bs52WmhR1rxw',
    appId: '1:894095534606:web:027f04a7b3b905e2c3ea5f',
    messagingSenderId: '894095534606',
    projectId: 'zein-clothes-shop',
    authDomain: 'zein-clothes-shop.firebaseapp.com',
    storageBucket: 'zein-clothes-shop.firebasestorage.app',
    measurementId: 'G-CZ15X2VMLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcgXQR1zWVMcYzmy9picYbKCPgrHihkw',
    appId: '1:894095534606:android:0161431c1683783dc3ea5f',
    messagingSenderId: '894095534606',
    projectId: 'zein-clothes-shop',
    storageBucket: 'zein-clothes-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFLtHokOiXPiBFURhpzFzA91NsISypec',
    appId: '1:894095534606:ios:7ddb79c4d8a20c3cc3ea5f',
    messagingSenderId: '894095534606',
    projectId: 'zein-clothes-shop',
    storageBucket: 'zein-clothes-shop.firebasestorage.app',
    iosBundleId: 'com.example.gunshopWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFLtHokOiXPiBFURhpzFzA91NsISypec',
    appId: '1:894095534606:ios:7ddb79c4d8a20c3cc3ea5f',
    messagingSenderId: '894095534606',
    projectId: 'zein-clothes-shop',
    storageBucket: 'zein-clothes-shop.firebasestorage.app',
    iosBundleId: 'com.example.gunshopWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaCZP2tdOYiKr8Z6a90O2Bs52WmhR1rxw',
    appId: '1:894095534606:web:20e5a2fc8104282cc3ea5f',
    messagingSenderId: '894095534606',
    projectId: 'zein-clothes-shop',
    authDomain: 'zein-clothes-shop.firebaseapp.com',
    storageBucket: 'zein-clothes-shop.firebasestorage.app',
    measurementId: 'G-BCBX6K92ZX',
  );
}
